volumes:
  point-db-volume: {}
  reverse-proxy-volume: {}

networks:
  reverse-proxy-net:
    driver: bridge

  backend-net:
    driver: bridge

  security-net:
    driver: bridge

services:
  points-db:
    container_name: points-db
    image: bitnami/postgresql:15.2.0
    environment:
      POSTGRESQL_DATABASE: points-db
      POSTGRESQL_USERNAME: dev-user
      POSTGRESQL_PASSWORD: dev-password
    volumes:
      - point-db-volume:/bitnami/postgresql
    networks:
      - backend-net
    ports:
      - "5432:5432"

  attempt-resource-server:
    container_name: attempt-resource
    depends_on:
      - points-db
    build:
      context: .
      dockerfile: keycloak-resource-server/Dockerfile
    networks:
      - backend-net
      - reverse-proxy-net
    ports:
      - "8090:8090"

  reverse-proxy:
    container_name: reverse-proxy
    image: bitnami/nginx:latest
    volumes:
      - reverse-proxy-volume:/bitnami/nginx
      - ./application-frontend/dist/application-frontend/browser:/app
      - ./conf/reverse-proxy.conf:/opt/bitnami/nginx/conf/server_blocks/reverse-proxy.conf
    networks:
      - reverse-proxy-net
    ports:
      - "8080:8080"
